services:
  mariadb:
    image: mariadb:11.5.2
    container_name: flower-mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  api:
    build:
      context: .
    container_name: flower-api
    env_file: .env
    depends_on:
      - mariadb
    ports:
      - "8060:8000"
    command: >
      bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app

volumes:
  mariadb-data:
