apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower-api
  template:
    metadata:
      labels:
        app: flower-api
    spec:
      containers:
        - name: flower-api
          image: elinemoerman219/flower-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: mariadb
            - name: DB_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: flower-api
spec:
  selector:
    app: flower-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
